name: GAS CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore clasp credentials from secrets
        run: |
          echo '{
            "token": {
              "access_token": "${{ secrets.ACCESS_TOKEN }}",
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.deployments",
              "token_type": "Bearer",
              "expiry_date": 9999999999999
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENTID }}",
              "clientSecret": "${{ secrets.CLIENTSECRET }}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }' > ~/.clasprc.json

      - name: Push to GAS
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
        run: clasp push --force
